from config import base

url = base.url
uname = base.uname
pw = base.pw

raw_input_data = base.RAW_INPUT_DATA
DATA_PROCESSED_OUT_DIR = base.DATA_PROCESSED_OUT_DIR

NODES_CSV = base.NODES_CSV
EDGES_CSV = base.EDGES_CSV

OUTPUT_PATH = base.OUTPUT_PATH
BEST_GNN_HYBRID_PATH = base.BEST_GNN_HYBRID_PATH

RETRAINED_OUTPUT_FILE = base.RETRAINED_OUTPUT_FILE
RESULTS_CLAIMS_FILE = base.RESULTS_CLAIMS_FILE

FINAL_REPORT_CSV = base.FINAL_REPORT_CSV

test_size = base.TEST_SIZE
skip_gnn_training = base.SKIP_GNN_TRAINING